name: dl-workshop
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- jupyter
- jupyterlab
- conda
- mamba
- scikit-learn
- numpy
- scipy
- matplotlib
- seaborn
- nodejs
- ipywidgets
- pyyaml
- pyjanitor
- tqdm
- pip
- nodejs
- holoviews
- hvplot
- bokeh
- pip:
  - jax
  - jaxlib
